### Compute gene weights

Combine evidence from multiple datasets in a single gene-level score.

```{r results = 'asis', fig.width = 6, fig.height = 6}
# create a dataframe with combined gene weights
gene_pvals <- gene_weights %>%
  select(ends_with('pval'))

# count number of missing values per gene
num_missing <- apply(gene_pvals, 1, function(x) { sum(is.na(x)) })

# compute -log10 of the median p-values for each gene
median_pvals <- apply(gene_pvals, 1, function(x) {
  -log10(median(x, na.rm = TRUE))
})

# create a dataframe to store combined gene scores
gene_scores <- tibble(
  symbol = gene_weights$gene_symbol,
  score = median_pvals,
  num_missing
)

# add metadata and sort
gene_mdat <- grch37 %>%
  select(symbol, biotype, description) %>%
  group_by(symbol) %>%
  slice(1)

gene_scores <- gene_scores %>%
  inner_join(gene_mdat, by = 'symbol') %>%
  arrange(desc(score))

#sum(is.na(gene_scores$score))
# [1] 40

# drop any genes with missing scores
gene_scores <- gene_scores[!is.na(gene_scores$score), ]

# create a version with outliers clipped for better visualizations
gene_scores_clipped <- gene_scores %>%
  filter(score < quantile(gene_scores$score, 0.99))

ggplot(gene_scores_clipped, aes(x = score)) +
  geom_density(alpha = 0.5)

# scatter plot of # missing vs. scores
set.seed(1)
ind <- sample(nrow(gene_scores_clipped), 1000)

ggplot(gene_scores_clipped[ind, ], aes(x = score, y = num_missing)) +
  geom_point()

# store gene scores
write_csv(gene_scores, file.path(output_dir, 'combined', 'gene_weights.csv'))
```

### Top Genes

```{r top_gene_scores, results = 'asis'}
gene_scores %>% 
  head(20) %>%
  kable
```

#### Functional Enrichment (Gene Scores)

```{r fgsea, results = 'asis', warning = FALSE, message = FALSE}
gene_stats <- setNames(gene_scores$score, gene_scores$symbol)

fgsea_results <- NULL

for (gene_set in names(gene_sets)) {
  set.seed(1)

  message(sprintf('Measuring enrichment for %s...', gene_set))

	res <- fgsea(gene_sets[[gene_set]], gene_stats, nperm = FGSEA_NPERM, nproc = MAX_THREADS) %>%
		select(-leadingEdge) %>%
		arrange(padj)

  res_sig <- res %>%
    filter(padj < 0.05)

	if (nrow(res_sig) > 0) {
    cat(sprintf("\n##### %s (n = %d)\n", gene_set, nrow(res_sig)))
	  print(kable(head(res_sig, 20)))

    fgsea_results <- rbind(fgsea_results, cbind(gene_set, res_sig))
	}
}

fgsea_results <- fgsea_results %>%
  arrange(padj)

cat(sprintf("- **Total Enriched**: %d\n", nrow(fgsea_results)))

write_csv(fgsea_results, file.path(fgsea_dir, 'fgsea_covariate_score_results.csv'))
```

#### Functional Enrichment - Top Collections (Gene Scores)

```{r results='asis'}
fgsea_results %>%
  group_by(gene_set) %>%
  summarize(n = n(), mean_pval = mean(padj)) %>%
  arrange(desc(n)) %>%
  kable
```


