```{r load_libraries, message = FALSE}
library(annotables)
library(doParallel)
library(DataExplorer)
library(diptest)
library(e1071)
library(foreach)
library(GSEABase)
library(fgsea)
library(heatmaply)
library(knitr)
library(NMF)
library(survival)
library(tidyverse)
library(viridisLite)
```

```{r shared_setup}
# general options
options(stringsAsFactors = FALSE)
options(digits = 3)
options(knitr.duplicate.label = 'allow')
#options(warn = 2)

# default plot options
opts_chunk$set(
  autodep = TRUE,
  fig.width = 4.8,
  fig.height = 3.6,
  fig.retina = 1,
  dpi = 300
)
# make reproducible
set.seed(1)

# base and data directories
public_data_dir <- '/data/public/human'

base_dir   <- normalizePath(file.path(getwd(), '..'))
input_dir  <- file.path(base_dir, 'input')
geo_dir    <- file.path(public_data_dir, 'geo')
mmrf_dir   <- file.path(public_data_dir, 'mmrf_commpass/IA13')

output_dir <- file.path(base_dir, 'output', VERSION)

gene_pvals_dir    <- file.path(output_dir, 'gene_pvals')
gene_stats_dir    <- file.path(output_dir, 'gene_stats')
pathway_pvals_dir <- file.path(output_dir, 'pathway_pvals')
pathway_stats_dir <- file.path(output_dir, 'pathway_stats')

fgsea_dir    <- file.path(output_dir, 'gene_fgsea')
gset_dir     <- file.path(output_dir, 'gene_sets')

combined_dir <- file.path(output_dir, 'combined')

for (dir_ in c(gene_pvals_dir, gene_stats_dir, pathway_pvals_dir, pathway_stats_dir, combined_dir, fgsea_dir, gset_dir)) {
  if (!dir.exists(dir_)) {
    dir.create(dir_, mode = '0755', recursive = TRUE)
  }
}

opts_knit$set(root.dir = base_dir)

# output directory
#today <- format(Sys.time(), '%Y-%m-%d')

# ggplot theme
theme_bw_high_res <- function (base_size = 11, base_line_size = 0.5) { 
	theme_bw(base_size = base_size) %+replace% 
    theme(plot.title = element_text(size = 9, vjust = 0), 
          legend.text = element_text(size = 8))
}

# maximum number of threads to use for parallel processes
MAX_THREADS <- max(1, min(detectCores() - 4, MAX_THREADS, na.rm=TRUE))
```
