---
title: Multiple Myeloma Dataset Comparison
author: V. Keith Hughitt
date: "`r format(Sys.time(), '%d %B, %Y') `"
output:
  html_document:
    toc: true
    number_sections: true
---

<!--

TODO July 15, 2019:

- do a quick test in dev/ to compare effect of using test statistics vs. p-values:
  - compute scores using each and measure enrichment with fgsea
  - if p-values work as well / better, than we can stop storing test statistic?
- for each dataset, split weights matrix up into:

  1. gene statistics (mean, median, sd, etc.)
  2. gene p-values
  3. gene test statistics

- Note: not all variables have associated p-values (some are R^2)
  - for individual datasets, store raw p-values, test stats, r^2
  - when combining below, drop the test stats and do:
      weights = [pvals, r^2 vals]
  - normalize to allow comparison..

-->

# Setup

```{r child='rmd/setup.Rmd'}
```

```{r settings}
# maximum ratio of covariate variables to allow before exluding a gene
# from the final score computation
GENE_MAX_MISSING_COVARIATES <- 0.5

# minimum number of genes required for gene set to be included in analysis
GENE_SET_MIN_SIZE <- 5
```

```{r rmarkdown_settings, include = FALSE}
# stop on encountered an error in a child rmd file
opts_chunk$set(error = FALSE)
opts_knit$set(verbose = TRUE)
```

# Overview

Summary of datasets included in this analysis:

```{r child='rmd/dataset_summary.Rmd'}
```

# Methods

```{r child='rmd/load_gene_sets.Rmd'}
```

```{r child='rmd/load_geo.Rmd'}
```

```{r child='rmd/load_mmrf.Rmd'}
```

```{r child='rmd/combine_gene_weights.Rmd'}
```

```{r child='rmd/combine_pathway_weights.Rmd'}
```

# Results

```{r child='rmd/results_overview.Rmd'}
```

```{r child='rmd/results_dataset_similarity.Rmd'}
```

```{r child='rmd/results_functional_enrichment.Rmd'}
```

```{r child='rmd/results_covariate_similarity.Rmd'}
```

```{r child='rmd/results_gene_scores.Rmd'}
```

```{r child='rmd/results_gene_set_scores.Rmd'}
```

# System information

```{r, collapse=FALSE}
sessionInfo()
```

```{r git_commit}
system('git rev-parse --short HEAD', intern = TRUE)
```

```{r save_html, include=FALSE}
system(sprintf('(sleep 15 && cp README.html %s) &', output_dir))
```

